// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNl-t-doiv3OCKKIs3ctLU3kmI4ES2Y8',
    appId: '1:125727304816:web:305cf3429881691d45d8b5',
    messagingSenderId: '125727304816',
    projectId: 'sehatmentalku-d56af',
    authDomain: 'sehatmentalku-d56af.firebaseapp.com',
    storageBucket: 'sehatmentalku-d56af.appspot.com',
    measurementId: 'G-BRTRMV6J58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN1zwmOhDs49DG6P29-_nifXBYg7yqXUw',
    appId: '1:125727304816:android:c1816394dada820c45d8b5',
    messagingSenderId: '125727304816',
    projectId: 'sehatmentalku-d56af',
    storageBucket: 'sehatmentalku-d56af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ6gyaVmIosJAQJ2Y_8o1PcXRHOrxhU5I',
    appId: '1:125727304816:ios:cfef7d627efeadd845d8b5',
    messagingSenderId: '125727304816',
    projectId: 'sehatmentalku-d56af',
    storageBucket: 'sehatmentalku-d56af.appspot.com',
    iosClientId: '125727304816-780v4srdh5b73cqq1kab4t8qo0ukgoie.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsehat',
  );
}
